### ISSUE TITLE
Youtube not playing directly

### ISSUE THREAD

**Issue by julien2810** [eouia/MMM-AssistantMk2#142]
Hello,

I am a little stuck with a configuration.

I can not start the youtube video with the voice.
The video is displayed, but it does not start.
Then my mirror is blocked.

My configuration is:

A raspberry pi 3 B

USB audio output and adapter "hw: 1,0"
Micro USB input and adapter "hw: 1.0"

What I put in the config file: /home/pi/MagicMirror/config

```
{
    module: "MMM-AssistantMk2",
    position: "top_left",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1",
      },

      notifications: {
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
      },
    }
  },
  {
    module: "MMM-Hotword",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1",
      },
      autostart:true,
      onDetected: {
        notification: function (payload) {
          return "ASSISTANT_ACTIVATE"
        },
        payload: function (payload){
          return {
            profile: payload.hotword
          }
        }
      },
    },
  },
		
		
		

		{
  module: 'MMM-Hotword',
  config: {
    snowboy: [
  {
    hotwords: "smartmirror", //this will be sent to other module for distinguishing which hotword is detected.
    file: "resources/models/smart_mirror.umdl",
    sensitivity: '0.5',
  },
  {
    hotwords: "snowboy",
    file: "resources/models/snowboy.umdl",
    sensitivity: '0.5',
  },
  {
    file: 'resources/models/jarvis.umdl',
    sensitivity: '0.8,0.80',
    hotwords: ['jarvis','jarvis'] //Kitt.ai changed their Jarvis UMDL, it has 2 models in one file. So weird.
    //anyway, you can give different name for each. ['jarvis_1', 'jarvis_2']. Even though I think this is useless.
  }
    ],
    record: {
      sampleRate    : 16000,      // audio sample rate
      threshold     : 0.5,        // silence threshold (rec only)
      thresholdStart: null,       // silence threshold to start recording, overrides threshold (rec only)
      thresholdEnd  : null,       // silence threshold to end recording, overrides threshold (rec only)
      silence       : 1.0,        // seconds of silence before ending
      verbose       : false,      // log info to the console. Use this when you want to check mic working or not.
      recordProgram : 'arecord',  // Defaults to 'arecord' - also supports 'rec' and 'sox'
      device        : null        // recording device (e.g.: 'plughw:1')
    },
    autostart: true,              // if 'false', this module will wait for 'HOTWORD_RESUME' notification to start hotwords detection at the beginning.
    autorestart: false,          // You can set this 'true' when you want this module to go back to listening mode automatically again after hotword is detected. But use this carefully when your other modules are using microphone or speaker.

    // customizable notification trigger
    notifications: {
      PAUSE: "HOTWORD_PAUSE",
      RESUME: "HOTWORD_RESUME",
      LISTENING : "HOTWORD_LISTENING",
      SLEEPING : "HOTWORD_SLEEPING",
      ERROR : "HOTWORD_ERROR",
    },
    onDetected: {
      notification: (payload) => {
        return "HOTWORD_DETECTED"
      },
      payload: (payload) => {
        return payload
      }
    },
  }
},
```

Configuration file: /home/pi/MagicMirror/modules/MMM-AssistantMk2

```
    youtubeAutoplay: true,
    spotifyAutoplay: true,
    pauseOnYoutube:true,
    youtubePlayerVars: { // You can set youtube playerVars for your purpose, but should be careful.
      "controls": 0,
      "loop": 1,
      "rel": 0,
    },
    youtubePlayQuality: "small", //small, medium, large, hd720, hd1080, highres or default
```

	
	
Here is the LOG from npm start dev :

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start', 'dev' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose config Skipping project config: /home/pi/.npmrc. (matches userconfig)
5 verbose stack Error: missing script: start
5 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:155:19)
5 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:63:5
5 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
5 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
5 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
5 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
5 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
5 verbose stack     at ReadFileContext.<anonymous> (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:332:20)
5 verbose stack     at ReadFileContext.callback (/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:237:13)
6 verbose cwd /home/pi
7 verbose Linux 4.14.98-v7+
8 verbose argv "/usr/bin/node" "/usr/bin/npm" "start" "dev"
9 verbose node v10.15.3
10 verbose npm  v6.4.1
11 error missing script: start
12 verbose exit [ 1, true ]
```

I tried this :

https://github.com/eouia/MMM-AssistantMk2/issues/65

responseScreen    is enabled

I tried removing the other modules and leaving only the wizard and Hotword.

Same result.

https://github.com/eouia/MMM-AssistantMk2/issues/38

I see here that you are talking about: useScreen: true
I can not find this configuration line.

Could you tell me where it is?

I also tried what you say here :  https://github.com/eouia/MMM-AssistantMk2/wiki/Usage

I do not use the command:

Play a video

but the one you say on the WIKI.

Name of the artist and song.

Do you have an idea ?

Thank you for your time.

**Comment by eouia** [comment]
Sorry for late reply. I was on Easter vacation. 
I think your configuration is totally wrong. Can you send me whole config.js to me? My email is `eouia0819@gmail.com`

**Comment by julien2810** [comment]
A huge thank you for your exceptional work and your time.
I sent you an e-mail containing the configuration files in text version not to be blocked by Outlook.

**Comment by julien2810** [comment]
Hello,

Have you had time to look at the configuration files that I sent to you by e-mail?

Have a nice day.

**Comment by eouia** [comment]
Sorry for late reply. I haven't be noticed a mail from you. Maybe it was a fault of my mailbox.
Anyway;
There seems no syntax error itself in your config. But You have duplicated MMM-Hotword configuration. Remove one latter.

**Comment by julien2810** [comment]
Super fast response :)
I will do that.

And :

I see here that you are talking about: useScreen: true
I can not find this configuration line.

Could you tell me where it is?

Very thanks for your time.

**Comment by eouia** [comment]
:D. It was totally misunderstanding between us. Our intent was `responseScreen: true,` but no matter what both of us understand it. :D
Anyway, If you are using only above configuration, it's value will be `true` by default, so you don't need to concern it.

**Comment by julien2810** [comment]
Ok ok super :)
I am very grateful for your help.
I will try having removed the second configuration of Hotword.
If I see that I still have a problem of launching video, I contact you by email.
Have a great day.

PS: Again, great work.

**Comment by eouia** [comment]
I'll close this issue. Wish a good luck.
