### ISSUE TITLE
Mk2가 동작을 안합니다.

### ISSUE THREAD

**Issue by MagicM19** [eouia/MMM-AssistantMk2#163]
AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.

    at Object.exports.createStatusError (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:91:15)

    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:233:26)

    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:211:8)

    at Object.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1306:15)

    at InterceptingListener._callNext (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:568:42)

    at InterceptingListener.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:618:8)

    at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1123:18

  code: 14,

  metadata:

   Metadata { _internal_repr: { 'content-disposition': [Array] } },

  details: 'Service unavailable.' }

{ Error: spawn ENOMEM

    at ChildProcess.spawn (internal/child_process.js:357:11)

    at spawn (child_process.js:540:9)

    at LPCM16.start (/home/pi/MagicMirror/modules/MMM-Hotword/components/lpcm16.js:101:15)

    at Class.startListening (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:217:14)

    at Class.activate (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:175:10)

    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:72:16)

    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)

    at Socket.emit (events.js:182:13)

    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12

    at process._tickCallback (internal/process/next_tick.js:61:11) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }

mmap() failed: 메모리를 할당할 수 없습니다

Failed to create permanent mapping for memfd region with ID = 3143604663

mmap() failed: 메모리를 할당할 수 없습니다

Failed to create permanent mapping for memfd region with ID = 1435812084

Ignoring received block reference with non-registered memfd ID = 1435812084

에러로그입니다. 
처음 핫워드로 동작합니다. 딩동 소리와 마이크모양 아이콘이 뜨고 동작을 멈추고
커뮤니케이션 오류가 발생합니다. 
두번째로 다시 핫워드를 불렀을 때 정상적으로 동작했다가
세번째부터는 핫워드도 동작을 멈춤니다. 
config도 한번 고쳤었는데 잘안되 더라고요
어떻게 고쳐야할지 감이 안와서 문의 드립니다.

**Comment by eouia** [comment]
일단 AMK2 의 문제인지 Hotword의 문제인지 확인해봐야 하므로, AMK2는 디스에이블 시키고 Hotword만 실행시켜서 트라이해보세요.

**Comment by eouia** [comment]
그리고 첫번째 Service Unavailable이 나오면 대개는 마이크에 문제가 생길 경우인데요, 아마 Hotword가 제대로 종료가 되지 않은 상태에서 AMK2 실행이 시도되서 그럴 겁니다. 왜 Hotword종료가 안되었는지는 로그 등이 있어야겠네요.

**Comment by MagicM19** [comment]
[HOTWORD] begins.

[HOTWORD] Detector starts listening.

[HOTWORD] Detected: snowboy

[HOTWORD] stops.

[HOTWORD] Final Result: { detected: true, hotword: 'snowboy', file: null }

[HOTWORD] begins.

[HOTWORD] Detector starts listening.

[HOTWORD] Detected: smartmirror

[HOTWORD] stops.

[HOTWORD] Final Result: { detected: true, hotword: 'smartmirror', file: null }

[HOTWORD] begins.

[HOTWORD] Detector starts listening.

[HOTWORD] Detected: snowboy

[HOTWORD] stops.

[HOTWORD] Final Result: { detected: true, hotword: 'snowboy', file: null }

[HOTWORD] begins.

[HOTWORD] Detector starts listening.

[HOTWORD] Detected: smartmirror

[HOTWORD] stops.

[HOTWORD] Final Result: { detected: true, hotword: 'smartmirror', file: null }

[HOTWORD] begins.

[HOTWORD] Detector starts listening.

[HOTWORD] Detected: snowboy

[HOTWORD] stops.

[HOTWORD] Final Result: { detected: true, hotword: 'snowboy', file: null }

[HOTWORD] begins.

[HOTWORD] Detector starts listening.

이런식의 로그가 나오는데  비정상적인 종료인가요?

**Comment by eouia** [comment]
hotword 자체는 정상이네요. 그런데 핫워드 인식하고 amk2로 제어를 넘길려면 "restart:false"로 핫워드를 종료해줘야하는데 안하신 것 같네요. command.md 읽어보세요

**Comment by MagicM19** [comment]
감사합니다 문제는 해결했습니다.
근데 구글 어시스턴트 메세지가 top_center 위치에서 
겹쳐져서 이상하게 나오는데 이건 어떻게 해결하는지 알수있을까요?

**Comment by eouia** [comment]
center 영역의 CSS가 좀 tricky 해서요... 다른 영역을 쓰시거나, center영역의 CSS를 변경하셔야 해요. 강제로 transform을 시켜버려서...
