### ISSUE TITLE
Node auth-and_test issue

### ISSUE THREAD

**Issue by adecker21** [eouia/MMM-AssistantMk2#179]
When I go to type in node auth_and_test.js I get the error code as follows

pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2 $ node auth_and_test.js
/home/pi/MagicMirror/modules/node_modules/grpc/src/grpc_extension.js:58
    throw e;
    ^

Error: Failed to load /home/pi/MagicMirror/modules/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc/grpc_node.node. /home/pi/MagicMirror/modules/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc/grpc_node.node: Unable to run arch-specific checks

    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Comment by eouia** [comment]
You've might have failed or missed something on installation steps. I think reinstall might be needed.

**Comment by adecker21** [comment]
I have redone all of the steps multiple times now and now I am coming up with this error code.
node auth_and_test.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/credentials.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at new Auth (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/components/auth.js:26:15)
    at new GoogleAssistant (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/index.js:21:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/auth_and_test.js:60:19)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

There is not a folder called credentials within my MMM-AssistantMk2 folder. should there be? I have my downloaded client id file saved in the mk2 folder though

**Comment by adecker21** [comment]
also, I don't think I have correctly registered the model.  I cannot get this link to work https://console.actions.google.com/u/[0]/project/[yourprojectId]/deviceregistration/

I am slightly confused due to the 2 sets of []. If my project ID was (for example) MagicMirror, would this link be:
https://console.actions.google.com/u/[0]/project/MagicMirror/deviceregistration/

**Comment by eouia** [comment]
First, you've missed `credentials.json`
https://github.com/eouia/MMM-AssistantMk2/wiki/Installation#get-auth-and-credentials-to-make-profile

Second.
`[0]` is not important.
Just go to https://consloe.actions.google.com  then login. Find your project (If there be several projects), Then See left side of menus. You can find your "devices" or "register device" menu (Or whatever, Sorry, I cannot remember at this moment, and I'm not in front of machine, so I can't tell the exact name)

**Comment by adecker21** [comment]
is the credentials.json downloaded during the registering process? I have downed the the "other client 1" client ID json file, but I believe you mean something different. 

I am still unable to find the registration steps. Firstly, I am unable to find ANYTHING  on the google console action page in ANY menu  resembling the phrase "Device" or "Register device".  Not only that, but the link that you recommended using to find the register page will not work either. 
Lets pretend my project ID is "MM1234" what url would I use? 
https://console.actions.google.com/u/[0]/project/MM1234/deviceregistration/                       ???????

**Comment by adecker21** [comment]
I finally found out how to register the device. I think I was already doing it in a roundabout way. I still do not have any file named "credentials.json". Should my "client_secret......json" file be located in a file called "credentials.json" or directly in the file "MMM-AssistantMk2'???

**Comment by Marcreed48** [comment]
https://youtu.be/UBgH5hejYtM
It helped me.

**Comment by eouia** [comment]
@adecker21 rename the file `client_secret_whatever.json` to `credentials.json` and use it.

**Comment by eouia** [comment]
Have you got still problem? I'll close this issue because there is no feedback anymore. Wish a good luck.

**Comment by b4cyte** [comment]
I am having a similar problem. I don’t have a credentials file in MMM-AssistantMk2, so I followed you advice and changed my client_secret_#####%%%%### to credentials.json. I ran node auth_and_test.js in the ~MagicMirror/modules/MMM-AssistantMk2 $, and get the Error: Cannot find module ‘/home/pi/MagicMirror/modules/MMM-AssistantMk2/credentials.json

What am I missing?

**Comment by eouia** [comment]
Check the location of `credentials.json`. It should be under `/home/pi/MagicMirror/modules/MMM-AssistantMk2/`
