### ISSUE TITLE
MMM-AssistantMk2 causes black screen on MM startup

### ISSUE THREAD

**Issue by prosynek20** [eouia/MMM-AssistantMk2#188]
OS: Raspbian Stretch
Pi: 3b+

I installed magic mirror then tested it and everything worked fine. I installed AssistantMk2 and added the configuration to my config.js file and now magic mirror only shows up with a black display.

This what I added to my config:
{
  			module: "MMM-AssistantMk2",
  			position: "top_right",
  			config: {
    				useWelcomeMessage: "brief today"
  				}
		},

This is the error I get when I run DISPLAY=:0 npm start in my MagicMirror directory:
Starting MagicMirror: v2.8.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Remote-Control
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v3.1-linux-arm-glibc
Found: [node-v64-linux-arm-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/pi/MagicMirror/node_modules/grpc/src/node/extension_binary/electron-v3.1-linux-arm-glibc/grpc_node.node'
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Remote-Control
App threw an error during load
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v3.1-linux-arm-glibc
Found: [node-v64-linux-arm-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/pi/MagicMirror/node_modules/grpc/src/node/extension_binary/electron-v3.1-linux-arm-glibc/grpc_node.node'
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/grpc/src/grpc_extension.js:53:17)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/grpc/src/grpc_extension.js:64:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/grpc/src/client_interceptors.js:144:12)
Whoops! There was an uncaught exception...
{ Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v3.1-linux-arm-glibc
Found: [node-v64-linux-arm-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/pi/MagicMirror/node_modules/grpc/src/node/extension_binary/electron-v3.1-linux-arm-glibc/grpc_node.node'
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/grpc/src/grpc_extension.js:53:17)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/grpc/src/grpc_extension.js:64:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/grpc/src/client_interceptors.js:144:12) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: calendar
Stopping module helper: newsfeed
Whoops! There was an uncaught exception...
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Class.stop (/home/pi/MagicMirror/modules/MMM-Remote-Control/node_helper.js:70:20)
    at App.stop (/home/pi/MagicMirror/js/app.js:247:16)
    at App.app.on (/home/pi/MagicMirror/js/electron.js:110:7)
    at App.emit (events.js:182:13)
    at Object.exports.execute (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/menu-item-roles.js:272:19)
    at MenuItem.click (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/menu-item.js:54:16)
    at Function.executeCommand (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/menu.js:31:13)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: calendar
Stopping module helper: newsfeed
Whoops! There was an uncaught exception...
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Class.stop (/home/pi/MagicMirror/modules/MMM-Remote-Control/node_helper.js:70:20)
    at App.stop (/home/pi/MagicMirror/js/app.js:247:16)
    at App.app.on (/home/pi/MagicMirror/js/electron.js:110:7)
    at App.emit (events.js:182:13)
    at Object.exports.execute (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/menu-item-roles.js:272:19)
    at MenuItem.click (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/menu-item.js:54:16)
    at Function.executeCommand (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/menu.js:31:13)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

Please help!

**Comment by prosynek20** [comment]
Do I have to use Rasbian Buster?

**Comment by eouia** [comment]
You've missed or failed `electron-rebuild` on installation. Read the installation guide and try installation again. If you meet some problem on installation step, report me.

**Comment by eouia** [comment]
I'll close this issue because there is no more feedback. Feel free to reopen issues if you still have problems.
