### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by crimean7** [eouia/MMM-AssistantMk2#20]
Getting following error on node auth_and_test.js:

node auth_and_test.js
/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:57
    throw e;
    ^

Error: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/node-v59-linux-arm-glibc/grpc_node.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:683:18)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)

Help would be appreciated.

**Comment by eouia** [comment]
https://github.com/eouia/MMM-AssistantMk2#some-troubleshootings

Which device & OS are you using? RPI Z or 1 might be needed manual modules compiling. Raspbian Jessie also.

**Comment by crimean7** [comment]
Thanks a lot for quick response. Yes, I'm using Rpi 3 with Raspbian Jessie. Had issues with MagicMirror itself on Stretch. I'm gonna try to troubleshoot MM on Stretch. Thanks.

**Comment by eouia** [comment]
I'll close this issue, Good luck to you
