### ISSUE TITLE
mode kiosk

### ISSUE THREAD

**Issue by frankoutch** [eouia/MMM-AssistantMk2#22]
Hello
I managed to run your module in french top
the only problem is that does not start in kisok mode (the screen is black !! ??)
will you have an idea?
ps: congratulations for your modules!

**Comment by eouia** [comment]
Give me more details, like error logs etc.

**Comment by frankoutch** [comment]
pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.4.1 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.4.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-NotificationTrigger
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-NotificationTrigger
App threw an error during load
Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:141:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:141:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.
> magicmirror@2.4.1 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.4.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-NotificationTrigger
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-NotificationTrigger
App threw an error during load
Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:141:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:141:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.

**Comment by frankoutch** [comment]
pi@raspberrypi:~ $ npm run config:check
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-09-18T19_26_17_972Z-debug.log
pi@raspberrypi:~ $

**Comment by eouia** [comment]
First, 
```
magicmirror@2.4.1 start /home/pi/MagicMirror
sh run-start.sh
```
That is not the command for `kiosk mode running` (unless you change the code inside of run-start.sh)

So your snowboy seems not compiled for `standalone` mode. you should compile it for Electron - the frontend of MagicMirror. Read the installation manual of MMM-Hotword : https://github.com/eouia/MMM-Hotword

And, your `npm run config:check` is wrong. it should be executed in MagicMirror direcotry.
```
cd ~/MagicMirror
npm run config:check
```
Anyway your problem is not about configuration. You've missed steps in your installation of `MMM-Hotword`

**Comment by frankoutch** [comment]
i do not understand

 pi @ raspberrypi: ~ $ cd MagicMirror
pi @ raspberrypi: ~ / MagicMirror $ npm run config: check

> magicmirror@2.4.1 config: check / home / pi / MagicMirror
> node tests / configs / check_config.js

Checking the file ... /home/pi/MagicMirror/config/config.js
Line 49 col 20 Missing semicolon.
pi @ raspberrypi: ~ / MagicMirror $

**Comment by eouia** [comment]
Don't mind `npm run config:check` at this moment. (`Missing semicolon.` is not a critical problem)

Your real problem is THIS;
```
Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
```
and it is not under the configuration. The error is saying you'd missed some steps when `MMM-Hotword` module was installed.

**Comment by frankoutch** [comment]
ok I need to reinstall the module MMM-Hotword?

**Comment by eouia** [comment]
Maybe? You need to read instructions carefully.

**Comment by frankoutch** [comment]
ok everything is working properly now
thanks to you

**Comment by eouia** [comment]
Good to you. I’ll close this issue.

**Comment by bachoo786** [comment]
> ok everything is working properly now
> thanks to you

How did you reinstall it? I have the same problem as you. Can you please help?

thanks.
