### ISSUE TITLE
./node_modules/.bin/electron-rebuild 이거를 실행하면 빨간색 에러문이 뜨면서 failed with exit code: 1이라고 뜹니다. 문의 결과 grpc를 1.13.0을 사용하면 된다는데 구글리을 해봐도 grpc를 downgrade하는 방법이 나와있지 않아서 질문드립니다. 혹시 아시나여??

### ISSUE THREAD

**Issue by JoonHoonKim** [eouia/MMM-AssistantMk2#225]
Failed with exit code: 1
    at SafeSubscriber._error (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/rxjs/internal/Subscriber.js:143:22)

**Comment by eouia** [comment]
에러 메시지가, 저건 결과고, 그 윗부분에 원인이 있을텐데요. 어떤 원인인지 모르면 답변드리기가...

그리고 1.13쓰는 건 벌써 옛날 이야기라서. 현재는 grpc@1.23.3 이 stable 버전입니다.

혹시 이 문제가 아닌가 싶긴 합니다.
https://github.com/eouia/MMM-AssistantMk2#some-more-troubleshooting

**Comment by JoonHoonKim** [comment]
> 에러 메시지가, 저건 결과고, 그 윗부분에 원인이 있을텐데요. 어떤 원인인지 모르면 답변드리기가...
> 
> 그리고 1.13쓰는 건 벌써 옛날 이야기라서. 현재는 grpc@1.23.3 이 stable 버전입니다.
> 
> 혹시 이 문제가 아닌가 싶긴 합니다.
> https://github.com/eouia/MMM-AssistantMk2#some-more-troubleshooting

링크에 있는데로 수행하니 정상적으로 Rebuild Complete 됐습니다. 정말 감사합니다!!ㅜㅜ
