### ISSUE TITLE
Faulty microphone on amk2 v3 version

### ISSUE THREAD

**Issue by tanhpkb** [eouia/MMM-AssistantMk2#270]
Please help me. Since I downloaded the amk2 v3 version, my mic has had a problem ..hotword still works normally. The first time when I started magic, the amk2 kick worked when I called the hot word..the 2nd call. The 3rd time amk2 still kicked the listening status but did not record my voice..I saw the terminal reported an error arecord .. I see my mic configuration is correct .. the config is also in the same format ..hotword is working normally .. I deleted and reinstalled many times but still got the same error .. my previous v2 version ok..mic works is ps3 eye. pls help me
All are the latest version
____________________________________
terminal:
[20:02:57.364] [LOG] [HOTWORD] Final Result: { detected: true, hotword: 'computer', file: null }
[20:02:57.480] [LOG] [AMK2] QUERY: { type: 'MIC',
profile: { profileFile: 'default.json', lang: 'en-US' },
key: null,
lang: null,
useScreenOutput: true,
useAudioOutput: true,
session: 1579611777388,
status: 'standby',
secretMode: false,
sayMode: false }
[20:02:57.612] [LOG] [AMK2:AS] MIC:RECORDING START.
[20:02:58.324] [LOG] [AMK2:AS] CONVERSATION:RESPONSE
[20:03:01.987] [LOG] [AMK2:AS] CONVERSATION:TRANSCRIPTION { transcription: 'mấy', done: false }
[20:03:02.206] [LOG] [AMK2:AS] CONVERSATION:TRANSCRIPTION { transcription: 'mấy giờ', done: false }
[20:03:02.239] [LOG] [AMK2:AS] CONVERSATION:TRANSCRIPTION { transcription: 'Mấy giờ rồi', done: false }
[20:03:02.578] [LOG] [AMK2:AS] CONVERSATION:TRANSCRIPTION { transcription: 'Mấy giờ rồi', done: false }
[20:03:02.702] [LOG] [AMK2:AS] CONVERSATION:TRANSCRIPTION { transcription: 'Mấy giờ rồi', done: false }
[20:03:03.244] [LOG] [AMK2:AS] CONVERSATION:END_OF_UTTERANCE
[20:03:03.246] [LOG] [AMK2:AS] MIC:RECORDING_END
[20:03:03.249] [LOG] [AMK2:AS] CONVERSATION:TRANSCRIPTION { transcription: 'Mấy giờ rồi', done: true }
[20:03:03.341] [LOG] [AMK2:AS] CONVERSATION:SCREEN object
[20:03:03.348] [LOG] [AMK2:AS] CONVERSATION:ACTION { requestId: '5e2fda97-0000-2a8f-8c3f-24058877ee10' }
[20:03:03.351] [LOG] [AMK2:AS] CONVERSATION:RESPONSE
[20:03:03.360] [LOG] [AMK2:AS] Recorder Error: arecord has exited with error code 1.

Enable debugging with the environment variable DEBUG=record.
[20:03:03.367] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.370] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.372] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.374] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.377] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.378] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.380] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.381] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.382] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.384] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.385] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.386] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.388] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.393] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.395] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.397] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.398] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.403] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.404] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.406] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.407] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.419] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.420] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.422] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.424] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.425] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.427] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.428] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.430] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.431] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.432] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.434] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.436] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.438] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.440] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.441] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.445] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.448] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.451] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.453] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.454] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.456] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.458] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.460] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.462] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.464] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.466] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.468] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.470] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.472] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.474] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.477] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.480] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.482] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.483] [LOG] [AMK2:AS] CONVERSATION:AUDIO 1600
[20:03:03.485] [LOG] [AMK2:AS] CONVERSATION:AUDIO 434
[20:03:03.489] [LOG] [AMK2:AS] CONVERSATION_ALL_RESPONSES_RECEIVED
[20:03:03.491] [LOG] [AMK2:AS] CONVERSATION_END:COMPLETED
[20:03:03.492] [LOG] [AMK2:AS] CONVERSATION_PP:RESPONSE_AUDIO_MAKING
[20:03:03.504] [LOG] [AMK2:BW] RESPONSE_WAV_FILE_CREATED
[20:03:03.506] [LOG] [AMK2:AS] CONVERSATION_PP:RESPONSE_AUDIO_CREATED tmp/lastResponse.wav
[20:03:03.590] [LOG] [AMK2] { session: 1579611777388,
error: null,
action: { requestId: '5e2fda97-0000-2a8f-8c3f-24058877ee10' },
text: null,
screen:
{ help: [ 'Bạn có thể làm gì?' ],
trysay: 'Try saying…',
links: [],
text:
'Luân Đôn, Vương Quốc Anh / Giờ địa phương\n13:03\nThứ Ba, 21 tháng 1, 2020\nThời gian ở Luân Đôn, Vương Quốc Anh',
photos: [],
path:
'/home/pi/MagicMirror/modules/MMM-AssistantMk2/tmp/lastScreenOutput.html',
uri: 'tmp/lastScreenOutput.html' },
audio:
{ path:
'/home/pi/MagicMirror/modules/MMM-AssistantMk2/tmp/lastResponse.wav',
uri: 'tmp/lastResponse.wav' },
transcription: { transcription: 'Mấy giờ rồi', done: true },
continue: false,
lastQuery:
{ type: 'MIC',
profile: { profileFile: 'default.json', lang: 'en-US' },
key: null,
lang: null,
useScreenOutput: true,
useAudioOutput: true,
session: 1579611777388,
status: 'standby',
secretMode: false,
sayMode: false } }
[20:03:05.710] [LOG] [HOTWORD] begins.
[20:03:05.713] [LOG] [HOTWORD] Detector starts listening.
[20:03:11.289] [LOG] [HOTWORD] Detected: computer
[20:03:11.291] [LOG] [HOTWORD] stops.
[20:03:11.294] [LOG] [HOTWORD] Final Result: { detected: true, hotword: 'computer', file: null }
[20:03:11.329] [LOG] [AMK2] QUERY: { type: 'MIC',
profile: { profileFile: 'default.json', lang: 'en-US' },
key: null,
lang: null,
useScreenOutput: true,
useAudioOutput: true,
session: 1579611791310,
status: 'standby',
secretMode: false,
sayMode: false }
[20:03:11.375] [LOG] [AMK2:AS] MIC:RECORDING START.
[20:03:11.390] [LOG] [AMK2:AS] Recorder Error: arecord has exited with error code 1.

Enable debugging with the environment variable DEBUG=record.
[20:03:11.929] [LOG] [AMK2:AS] CONVERSATION:RESPONSE
[20:03:41.882] [LOG] [AMK2:AS] CONVERSATION_ERROR : { Error: 14 UNAVAILABLE: Service unavailable.
at Object.exports.createStatusError (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:91:15)
at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:233:26)
at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:211:8)
at Object.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1306:15)
at InterceptingListener._callNext (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:568:42)
at InterceptingListener.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:618:8)
at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1123:18
code: 14,
metadata:
Metadata { _internal_repr: { 'content-disposition': [Array] }, flags: 0 },
details: 'Service unavailable.' }
[20:03:41.891] [LOG] [AMK2:AS] >> This error might happen when improper configuration or invalid Mic setup.
[20:03:41.893] [LOG] [AMK2] { session: 1579611791310,
error: 'NO_RESPONSE',
action: null,
text: null,
screen: null,
audio: null,
transcription: null,
continue: false,
lastQuery:
{ type: 'MIC',
profile: { profileFile: 'default.json', lang: 'en-US' },
key: null,
lang: null,
useScreenOutput: true,
useAudioOutput: true,
session: 1579611791310,
status: 'standby',
secretMode: false,
sayMode: false } }
[20:03:41.935] [LOG] [HOTWORD] begins.
[20:03:41.938] [LOG] [HOTWORD] Detector starts listening
_______________________________________________________________________
mic:
pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: CameraB409241 [USB Camera-B4.09.24.1], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by eouia** [comment]
Hmmm. I suspect some possible reasons;
First would be, your webcam mic is too slowly closed due to its h/w device characteristic. I recommend testing another USB mic (not webcam)
Or Just saying `computer, Mấy giờ rồi` at once flawlessly without waiting for a chime. It could be a help for slow opening and closing mic character.

**Comment by cdr93** [comment]
Hello,
I also have problems with the PS3Eye microphone.
When I run MagicMirror, everything works fine.
The wizard works on the first question. I can even have a conversation with him.
However, if the window closes, the microphone becomes ineffective.
If I refresh the mirror (alt + R) it works.
Is there a way to correct this problem?
I am enclosing my log file, my MMM-Hotwords and MMM-Assistant configurations as well as my asound.conf file.

`pi@raspberrypi:~ $ cd MagicMirror/
pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.10.1 start /home/pi/MagicMirror
> ./run-start.sh

[18:23:54.799] [LOG]    Starting MagicMirror: v2.10.1
[18:23:54.816] [LOG]    Loading config ...
[18:23:54.828] [LOG]    Loading module helpers ...
[18:23:54.830] [LOG]    No helper found for module: alert.
[18:23:55.001] [LOG]    Initializing new module helper ...
[18:23:55.003] [LOG]    Module helper loaded: updatenotification
[18:23:55.005] [LOG]    No helper found for module: clock.
[18:23:56.212] [LOG]    Initializing new module helper ...
[18:23:56.213] [LOG]    Module helper loaded: calendar
[18:23:56.214] [LOG]    No helper found for module: compliments.
[18:23:56.215] [LOG]    No helper found for module: currentweather.
[18:23:56.216] [LOG]    No helper found for module: weatherforecast.
[18:23:56.308] [LOG]    Initializing new module helper ...
[18:23:56.309] [LOG]    Module helper loaded: newsfeed
[18:23:59.524] [LOG]    Initializing new module helper ...
[18:23:59.526] [LOG]    Module helper loaded: MMM-AssistantMk2
[18:24:00.012] [LOG]    Initializing new module helper ...
[18:24:00.013] [LOG]    Module helper loaded: MMM-Hotword
[18:24:00.014] [LOG]    All module helpers loaded.
[18:24:00.015] [LOG]    Starting server on port 8080 ... 
[18:24:00.044] [LOG]    Server started ...
[18:24:00.046] [LOG]    Connecting socket for: updatenotification
[18:24:00.047] [LOG]    Connecting socket for: calendar
[18:24:00.048] [LOG]    Starting node helper for: calendar
[18:24:00.049] [LOG]    Connecting socket for: newsfeed
[18:24:00.050] [LOG]    Starting module: newsfeed
[18:24:00.051] [LOG]    Connecting socket for: MMM-AssistantMk2
[18:24:00.052] [LOG]    Connecting socket for: MMM-Hotword
[18:24:00.053] [LOG]    [HOTWORD] MMM-Hotword starts
[18:24:00.054] [LOG]    Sockets connected & modules started ...
[18:24:00.364] [LOG]    Launching application.
[18:24:04.158] [LOG]    Create new calendar fetcher for url: http://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics - Interval: 300000
[18:24:04.220] [LOG]    Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
[18:24:04.304] [LOG]    [HOTWORD] Recipe is loaded: with-AMk2v3_smart-mirror.js
[18:24:04.607] [LOG]    [HOTWORD] begins.
[18:24:04.611] [LOG]    [HOTWORD] Detector starts listening.
[18:24:46.589] [LOG]    [HOTWORD] Detected: SMARTMIRROR
[18:24:46.831] [LOG]    [HOTWORD] After Recording: 8000
[18:24:47.073] [LOG]    [HOTWORD] After Recording: 8000
[18:24:47.346] [LOG]    [HOTWORD] After Recording: 4000
[18:24:47.368] [LOG]    [HOTWORD] After Recording: 4000
[18:24:47.576] [LOG]    [HOTWORD] After Recording: 8000
[18:24:47.826] [LOG]    [HOTWORD] After Recording: 8000
[18:24:48.087] [LOG]    [HOTWORD] After Recording: 8000
[18:24:48.322] [LOG]    [HOTWORD] After Recording: 8000
[18:24:48.572] [LOG]    [HOTWORD] After Recording: 8000
[18:24:48.822] [LOG]    [HOTWORD] After Recording: 8000
[18:24:49.094] [LOG]    [HOTWORD] After Recording: 8000
[18:24:49.345] [LOG]    [HOTWORD] After Recording: 4000
[18:24:49.371] [LOG]    [HOTWORD] After Recording: 4000
[18:24:49.573] [LOG]    [HOTWORD] After Recording: 4000
[18:24:49.583] [LOG]    [HOTWORD] After Recording: 4000
[18:24:49.823] [LOG]    [HOTWORD] After Recording: 4000
[18:24:49.833] [LOG]    [HOTWORD] After Recording: 4000
[18:24:51.060] [LOG]    [HOTWORD] stops.
[18:24:51.063] [LOG]    [HOTWORD] After Recording finised. size: 104050
[18:24:51.071] [LOG]    [HOTWORD:B2W] WAV_FILE_CREATED: /home/pi/MagicMirror/modules/MMM-Hotword/temp/afterRecording.wav 104050
[18:24:51.074] [LOG]    [HOTWORD] Final Result: { detected: true,
  hotword: 'SMARTMIRROR',
  file: 'temp/afterRecording.wav' }

`
`{
  module: "MMM-AssistantMk2",
  position: "top_left",
  config: {
    assistantConfig: {
      latitude: 48.9192041,
      longitude: 2.530892,
	},
    micConfig: { // put there configuration generated by auto-installer
      recorder: "arecord",
      device: "plughw:1",
    },
  }
},
{
    module: "MMM-Hotword",
    position: "bottom_left",
    config: {
      useDisplay: false,
      chimeOnFinish: null,
      recipes: ["with-AMk2v3_smart-mirror.js"],
      mic: {
        recordProgram: "arecord",
        device: "plughw:1",
      },
    },`
`# ps3 eye + 3.5mm speaker Raspberry Pi
## Suggested by http://julius.sourceforge.jp/forum/viewtopic.php?f=9&t=66
## Modified by https://github.com/afzalive
pcm.jack {
  type hw
  card ALSA
}
pcm.array {
  type hw
  card CameraB409241
}
pcm.softvol {
  type softvol
  slave.pcm "jack"
  control {
    name Master
    card 0
  }
}
pcm.cap {
  type plug
  slave.pcm "array"
  slave.channels 4
  ttable {
    0.0 30.0
    1.1 30.0
  }
}
pcm.!default {
    type asym
    playback.pcm "plug:softvol"
    capture.pcm {
      type plug
      slave.pcm "cap"
    }
}
ctl.!default {
  type hw
  card 0
}
ctl.softvol {
  type hw
  card 0
}
`
Regards,

**Comment by cdr93** [comment]
Hello,
I managed to solve the problem which in fact was not but an error on my part.
You simply had to add in the configuration file of MMM-Assistantmk2 the line:

`  recipes: ["with-MMM-Hotword.js"],`

After this addition no more problems. The microphone cuts well and works again to the second question.
Sorry again ...

Thank you again for this superb module.
Regards,

**Comment by tanhpkb** [comment]
is there any other way .. I think the ps3 eye mic is a good device and the device you recommend to use it .. with v2 it all works fine .. just like you said. if i don't wait 1 the beep and talk immediately when calling from a computer, the mic works ok..but I prefer to wait for a beep..because everything is easier..more accurate .. please help me..there is a way do you reset the mic every time you say no ..

**Comment by tanhpkb** [comment]
tôi có rồi.Recipe: ["with -MMM-Hotword.js"],
nhưng vẫn lỗi..tôi thích cái mới..thích giao diện của bản v3..nhưng tôi thấy bản v2 ổn định..xin hãy giúp tôi với..cảm ơn bạn

**Comment by tanhpkb** [comment]
I have it. Ripe: ["with -MMM-Hotword.js"],
but still error..I like the new one..I like the interface of the v3..but I see the stable v2..please help me..thank you

**Comment by bugsounet** [comment]
we are working around this issue.
and correct it as soon as possible

**Comment by tanhpkb** [comment]
thank you very much..i wait for the error to be fixed

**Comment by bugsounet** [comment]
We updated AMk2 to 3.0.1, can you try it ?

**Comment by tanhpkb** [comment]
Let me try. I'll be back

**Comment by tanhpkb** [comment]
my mic is working fine .. you guys work really fast and effectively..thank you very much..happy

**Comment by bugsounet** [comment]
With pleasure,
Thanks. 

@eouia & @bugsounet

**Comment by tanhpkb** [comment]
I'm from Vietnam..Vietnam always welcomes you .. thank you
