### ISSUE TITLE
US Holiday calendar not loading

### ISSUE THREAD

**Issue by athavanraja** [eouia/MMM-AssistantMk2#306]
Dear friends,
Calendars from Calendarlab is not working. Other calendars are fine.

 Anybody else facing this issue? This has been working fine.

Error message in console.

[15:21:08.555] [LOG]    Whoops! There was an uncaught exception...
[15:21:08.558] [ERROR]  Error: Unknown RRULE property ''
    at /home/pi/MagicMirror/node_modules/rrule/dist/es5/rrule.js:1191:23
    at Array.forEach (<anonymous>)
    at parseRrule (/home/pi/MagicMirror/node_modules/rrule/dist/es5/rrule.js:1149:11)
    at parseLine (/home/pi/MagicMirror/node_modules/rrule/dist/es5/rrule.js:1132:16)
    at Array.map (<anonymous>)
    at Function.parseString (/home/pi/MagicMirror/node_modules/rrule/dist/es5/rrule.js:1110:41)
    at Function.RRule.fromString (/home/pi/MagicMirror/node_modules/rrule/dist/es5/rrule.js:2135:32)
    at Object.ical.objectHandlers.END (/home/pi/MagicMirror/modules/default/calendar/vendor/ical.js/node-ical.js:62:23)
    at Object.handleObject (/home/pi/MagicMirror/modules/default/calendar/vendor/ical.js/ical.js:400:41)
    at Object.parseICS (/home/pi/MagicMirror/modules/default/calendar/vendor/ical.js/ical.js:441:20)
[15:21:08.577] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[15:21:08.579] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

**Comment by bugsounet** [comment]
Sorry for this response but this page is only for MMM-AssistantMk2 issue. 

Please contact the developer of this module.

**Comment by athavanraja** [comment]
Apologies.
