### ISSUE TITLE
 PROBLEM TO CONFIRM A SECOND VOCAL COMMAND WITH GOOGLE ASISSTANT 

### ISSUE THREAD

**Issue by pascal006** [eouia/MMM-AssistantMk2#316]
Hi!! there!!
i’m using MMM-AssistantMK2 And MMM-Hotword

when a create a event in my google agenda with MMM-Hotword the first record is good but wen is time to confirm the command example : I say yes! to confirm she doesn’t understand the command yes . So the event is cancel and is not added in my agenda.

What can i do to solved that situation!!!
thank’s for your help guys

Using usb mic. 
Raspberry pi 3b

**Comment by bugsounet** [comment]
hi, i will do some test.

I 'll be back to you as soon as possible.

**Comment by bugsounet** [comment]
Can you set debug: true in you AMk2 [configuration](https://github.com/eouia/MMM-AssistantMk2/wiki/Configuration-Sample#full--detailed-see-the-configuration-structure) ?

Can you give me your MMM-Hotword and MMM-AssistantMk2 configuration (part of config.js file) ?

Can you give me back end log when your bug appears ?

**Comment by pascal006** [comment]
yes !!!,
so the the debug is set to true 

 module: "MMM-AssistantMk2",
  position: "top_right",
  config: {
    debug: true,
    ui: "Classic", // or "Classic", "Classic2","Fullscreen"
    assistantConfig: {
      projectId: "", // Required to use gaction.
      modelId: "", // (OPTIONAL for gaction)
      instanceId: "", // (OPTIONAL for gaction)
      latitude: 45.4772300,
      longitude: -75.7016400,
    },

here my config.js file 

{
  module: "MMM-AssistantMk2",
  position: "top_right",
  config: {
    ui: "Classic", // or "Classic", "Classic2","Fullscreen"
    assistantConfig: {
      projectId: "", // Required to use gaction.
      modelId: "", // (OPTIONAL for gaction)
      instanceId: "", // (OPTIONAL for gaction)
      latitude: 45.4772300,
      longitude: -75.7016400,
    },
    responseConfig: {
      useHTML5: true, // sound render by HTML5
      useScreenOutput: true,
      useAudioOutput: true,
      useChime: true,
      timer: 5000,
      myMagicWord: false,
      //Your prefer sound play program. By example, if you are running this on OSX, `afplay` could be available.
      playProgram: "mpg321", //needed if you don't use HTML5 sound render
      chime: {
        beep: "beep.mp3",
        error: "error.mp3",
        continue: "continue.mp3",
        open: "Google_beep_open.mp3",
        close: "Google_beep_close.mp3",
      },
      // false - animated icons, 'standby' - static icons only for standby state, true - all static icons
      useStaticIcons: false
    },
    micConfig: { // put there configuration generated by auto-installer
      recorder: "arecord",
      device: "plughw:1,",
    },
    customActionConfig: {
      autoMakeAction: false,
      autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
      actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
    },
    recipes: [ "with-MMM-Hotword.js", "with-MMM-TelegramBot.js" ],
    profiles: {
      "default": {
        profileFile: "default.json",
        lang: "en-US"
      }
    },
    addons: false,
  },
},
{
    module: "MMM-Hotword",
    position: "bottom_left",
    config: {
      useDisplay: false,
      chimeOnFinish: null,
      recipes: ["with-AMk2v3_smart-mirror.js"],
      mic: {
        recordProgram: "arecord",
        device: "plughw:1",
      },
    },
  },
and for the log error i dont no how to do it sorry for that !!!

**Comment by eouia** [comment]
First, you don't need all of these complex configurations at all. I warned it on docs.
Try to use this;
```
{
  module: "MMM-Hotword",
  position: "top_left",
  config: {
    recipes: ["with-AMk2v3_smart-mirror.js"],
    chimeOnFinish: null,
    mic: {
      recordProgram: "arecord",
      device: "plughw:1",
    },
  }
},
{
  module: "MMM-AssistantMk2",
  position: "top_left",
  config: {
    recipes: ["with-MMM-Hotword.js"],
    debug: true,
    ui: "Classic", // or "Classic", "Classic2","Fullscreen"
    assistantConfig: {
      latitude: 45.4772300,
      longitude: -75.7016400,
    },
  }
},
```
If success, you can add one-by-one what you need.

To display log;
```
pm2 stop all
cd ~/MagicMirror
npm start dev
```
Then let's see what happens in your terminal shell.

**Comment by pascal006** [comment]
thank's  
you are very kind for your help!!

i reinstall the configuration 
everything work good 

and here my log 

 magicmirror@2.10.1 start /home/pi/MagicMirror
> ./run-start.sh "dev"

[10:49:10.979] [LOG]    Starting MagicMirror: v2.10.1
[10:49:11.026] [LOG]    Loading config ...
[10:49:11.039] [LOG]    Loading module helpers ...
[10:49:11.044] [LOG]    No helper found for module: alert.
[10:49:11.150] [LOG]    Initializing new module helper ...
[10:49:11.151] [LOG]    Module helper loaded: updatenotification
[10:49:11.153] [LOG]    No helper found for module: clock.
[10:49:12.228] [LOG]    Initializing new module helper ...
[10:49:12.229] [LOG]    Module helper loaded: calendar
[10:49:12.234] [LOG]    No helper found for module: currentweather.
[10:49:12.236] [LOG]    No helper found for module: weatherforecast.
[10:49:12.312] [LOG]    Initializing new module helper ...
[10:49:12.313] [LOG]    Module helper loaded: newsfeed
[10:49:12.942] [LOG]    Initializing new module helper ...
[10:49:12.944] [LOG]    Module helper loaded: MMM-Hotword
[10:49:15.614] [LOG]    Initializing new module helper ...
[10:49:15.615] [LOG]    Module helper loaded: MMM-AssistantMk2
[10:49:16.901] [LOG]    Initializing new module helper ...
[10:49:16.903] [LOG]    Module helper loaded: MMM-NowPlayingOnSpotify
[10:49:16.904] [LOG]    All module helpers loaded.
[10:49:16.905] [LOG]    Starting server on port 8080 ... 
[10:49:16.944] [LOG]    Server started ...
[10:49:16.946] [LOG]    Connecting socket for: updatenotification
[10:49:16.947] [LOG]    Connecting socket for: calendar
[10:49:16.949] [LOG]    Starting node helper for: calendar
[10:49:16.950] [LOG]    Connecting socket for: newsfeed
[10:49:16.951] [LOG]    Starting module: newsfeed
[10:49:16.954] [LOG]    Connecting socket for: MMM-Hotword
[10:49:16.955] [LOG]    [HOTWORD] MMM-Hotword starts
[10:49:16.957] [LOG]    Connecting socket for: MMM-AssistantMk2
[10:49:16.960] [LOG]    Connecting socket for: MMM-NowPlayingOnSpotify
[10:49:16.962] [LOG]    Sockets connected & modules started ...
[10:49:17.572] [LOG]    Launching application.
[10:49:25.467] [LOG]    Create new calendar fetcher for url: https://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics - Interval: 120000
[10:49:25.713] [LOG]    Create new calendar fetcher for url: http://www.calendarlabs.com/templates/ical/US-Holidays.ics - Interval: 4000
[10:49:25.718] [LOG]    Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/pascalgascon006%40gmail.com/private-880c324eb8fad5ea58b14cfe98ea9063/basic.ics - Interval: 4000
[10:49:25.722] [LOG]    Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/gaus7v1hhkhqdrup8fjn379v74%40group.calendar.google.com/private-4ba8edec2cf4091f707763f716de292d/basic.ics - Interval: 4000
[10:49:25.794] [LOG]    Create new news fetcher for url: https://ici.radio-canada.ca/rss/4159 - Interval: 300000
[10:49:25.931] [LOG]    [HOTWORD] Recipe is loaded: with-AMk2v3_smart-mirror.js
[10:49:26.301] [LOG]    [AMK2] MMM-AssistantMk2 Version: 3.1.0-3
[10:49:26.383] [LOG]    [AMK2] AssistantMk2 is initialized.
[10:49:26.395] [ERROR]  (node:1459) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[10:49:26.398] [ERROR]  (node:1459) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[10:49:27.373] [LOG]    Refreshed access token because it has expired. Expired at: 10:49:25 now is: 10:49:27
[10:49:27.446] [LOG]    Refreshed access token because it has expired. Expired at: 11:49:27 now is: 10:49:27
[10:49:27.840] [LOG]    [HOTWORD] begins.
[10:49:27.884] [LOG]    [HOTWORD] Detector starts listening.
[10:51:22.545] [LOG]    [HOTWORD] Detected: SMARTMIRROR
[10:51:22.797] [LOG]    [HOTWORD] After Recording: 4000
[10:51:22.920] [LOG]    [HOTWORD] After Recording: 4000
[10:51:23.026] [LOG]    [HOTWORD] After Recording: 4000
[10:51:23.164] [LOG]    [HOTWORD] After Recording: 4000
[10:51:24.269] [LOG]    [HOTWORD] stops.
[10:51:24.281] [LOG]    [HOTWORD] After Recording finised. size: 16050
[10:51:24.352] [LOG]    [HOTWORD:B2W] WAV_FILE_CREATED: /home/pi/MagicMirror/modules/MMM-Hotword/temp/afterRecording.wav 16050
[10:51:24.355] [LOG]    [HOTWORD] Final Result: {
  detected: true,
  hotword: 'SMARTMIRROR',
  file: 'temp/afterRecording.wav'
}
[10:51:27.653] [LOG]    [HOTWORD] begins.
[10:51:27.663] [LOG]    [HOTWORD] Detector starts listening.
[10:51:35.833] [LOG]    [HOTWORD] Detected: SMARTMIRROR
[10:51:36.082] [LOG]    [HOTWORD] After Recording: 4000
[10:51:36.205] [LOG]    [HOTWORD] After Recording: 4000
[10:51:36.318] [LOG]    [HOTWORD] After Recording: 4000
[10:51:36.455] [LOG]    [HOTWORD] After Recording: 4000
[10:51:36.575] [LOG]    [HOTWORD] After Recording: 4000
[10:51:37.227] [LOG]    [HOTWORD] After Recording: 4000
[10:51:37.353] [LOG]    [HOTWORD] After Recording: 4000
[10:51:37.462] [LOG]    [HOTWORD] After Recording: 4000
[10:51:37.572] [LOG]    [HOTWORD] After Recording: 4000
[10:51:37.714] [LOG]    [HOTWORD] After Recording: 4000
[10:51:37.834] [LOG]    [HOTWORD] After Recording: 4000
[10:51:38.002] [LOG]    [HOTWORD] After Recording: 4000
[10:51:38.074] [LOG]    [HOTWORD] After Recording: 4000
[10:51:38.205] [LOG]    [HOTWORD] After Recording: 4000
[10:51:38.319] [LOG]    [HOTWORD] After Recording: 4000
[10:51:38.454] [LOG]    [HOTWORD] After Recording: 4000
[10:51:38.568] [LOG]    [HOTWORD] After Recording: 4000
[10:51:38.712] [LOG]    [HOTWORD] After Recording: 4000
[10:51:38.825] [LOG]    [HOTWORD] After Recording: 4000
[10:51:38.959] [LOG]    [HOTWORD] After Recording: 4000
[10:51:40.060] [LOG]    [HOTWORD] stops.
[10:51:40.063] [LOG]    [HOTWORD] After Recording finised. size: 80050
[10:51:40.068] [LOG]    [HOTWORD:B2W] WAV_FILE_CREATED: /home/pi/MagicMirror/modules/MMM-Hotword/temp/afterRecording.wav 80050
[10:51:40.069] [LOG]    [HOTWORD] Final Result: {
  detected: true,
  hotword: 'SMARTMIRROR',
  file: 'temp/afterRecording.wav'
}
[10:52:09.534] [LOG]    [HOTWORD] begins.
[10:52:09.561] [LOG]    [HOTWORD] Detector starts listening.
[10:52:26.222] [LOG]    [HOTWORD] Detected: SMARTMIRROR
[10:52:26.469] [LOG]    [HOTWORD] After Recording: 4000
[10:52:26.591] [LOG]    [HOTWORD] After Recording: 4000
[10:52:26.705] [LOG]    [HOTWORD] After Recording: 4000
[10:52:26.842] [LOG]    [HOTWORD] After Recording: 4000
[10:52:26.956] [LOG]    [HOTWORD] After Recording: 4000
[10:52:28.012] [LOG]    [HOTWORD] stops.
[10:52:28.036] [LOG]    [HOTWORD] After Recording finised. size: 20050
[10:52:28.103] [LOG]    [HOTWORD:B2W] WAV_FILE_CREATED: /home/pi/MagicMirror/modules/MMM-Hotword/temp/afterRecording.wav 20050
[10:52:28.112] [LOG]    [HOTWORD] Final Result: {
  detected: true,
  hotword: 'SMARTMIRROR',
  file: 'temp/afterRecording.wav'
}
[10:52:30.954] [LOG]    [HOTWORD] begins.
[10:52:30.956] [LOG]    [HOTWORD] Detector starts listening.
[10:52:37.420] [LOG]    [HOTWORD] Detected: SMARTMIRROR
[10:52:37.687] [LOG]    [HOTWORD] After Recording: 4000
[10:52:37.812] [LOG]    [HOTWORD] After Recording: 4000
[10:52:37.913] [LOG]    [HOTWORD] After Recording: 4000
[10:52:38.064] [LOG]    [HOTWORD] After Recording: 4000
[10:52:38.422] [LOG]    [HOTWORD] After Recording: 4000
[10:52:38.551] [LOG]    [HOTWORD] After Recording: 4000
[10:52:38.661] [LOG]    [HOTWORD] After Recording: 4000
[10:52:38.819] [LOG]    [HOTWORD] After Recording: 4000
[10:52:38.912] [LOG]    [HOTWORD] After Recording: 4000
[10:52:39.084] [LOG]    [HOTWORD] After Recording: 4000
[10:52:39.168] [LOG]    [HOTWORD] After Recording: 4000
[10:52:39.305] [LOG]    [HOTWORD] After Recording: 4000
[10:52:39.420] [LOG]    [HOTWORD] After Recording: 4000
[10:52:39.553] [LOG]    [HOTWORD] After Recording: 4000
[10:52:39.664] [LOG]    [HOTWORD] After Recording: 4000
[10:52:39.809] [LOG]    [HOTWORD] After Recording: 4000
[10:52:39.912] [LOG]    [HOTWORD] After Recording: 4000
[10:52:40.050] [LOG]    [HOTWORD] After Recording: 4000
[10:52:40.162] [LOG]    [HOTWORD] After Recording: 4000
[10:52:40.303] [LOG]    [HOTWORD] After Recording: 4000
[10:52:41.405] [LOG]    [HOTWORD] stops.
[10:52:41.413] [LOG]    [HOTWORD] After Recording finised. size: 80050
[10:52:41.445] [LOG]    [HOTWORD:B2W] WAV_FILE_CREATED: /home/pi/MagicMirror/modules/MMM-Hotword/temp/afterRecording.wav 80050
[10:52:41.447] [LOG]    [HOTWORD] Final Result: {
  detected: true,
  hotword: 'SMARTMIRROR',
  file: 'temp/afterRecording.wav'
}
[10:53:29.879] [LOG]    [HOTWORD] begins.
[10:53:29.914] [LOG]    [HOTWORD] Detector starts listening.
[10:54:07.207] [LOG]    Shutting down server...
[10:54:07.308] [LOG]    Stopping module helper: updatenotification
[10:54:07.324] [LOG]    Stopping module helper: calendar
[10:54:07.326] [LOG]    Stopping module helper: newsfeed
[10:54:07.328] [LOG]    Stopping module helper: MMM-Hotword
[10:54:07.331] [LOG]    Stopping module helper: MMM-AssistantMk2
[10:54:07.333] [LOG]    Stopping module helper: MMM-NowPlayingOnSpotify
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:413:19)
    at writeOrBuffer (_stream_writable.js:401:5)
    at WriteStream.Writable.write (_stream_writable.js:301:11)
    at Object.con.<computed> [as error] (/home/pi/MagicMirror/node_modules/console-stamp/main.js:148:46)
    at process.<anonymous> (/home/pi/MagicMirror/js/app.js:41:10)
    at process.emit (events.js:205:15)
    at process._fatalException (internal/process/execution.js:146:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! magicmirror@2.10.1 start: `./run-start.sh "dev"`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the magicmirror@2.10.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-02-17T15_54_12_520Z-debug.log

**Comment by eouia** [comment]
> everything work good

Can we close this issue? or still have another issue? (for another issue, post it as new issue)

**Comment by pascal006** [comment]
yes we can close this issue 
again thank
