### ISSUE TITLE
cannot find module 'play-sound'

### ISSUE THREAD

**Issue by Kris-014** [eouia/MMM-AssistantMk2#43]
{ Error: Cannot find module 'play-sound'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Class.play (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:24:20)
    at Class.playChime (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:42:10)
    at Class.prepareActivate (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:117:10)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:98:12)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11) code: 'MODULE_NOT_FOUND' }

**Comment by Kris-014** [comment]
I just try to update your module but i got this error when it pick up the Hotword... any idea?
