### ISSUE TITLE
Problems with Assistant module on RPi 3B+

### ISSUE THREAD

**Issue by radokristof** [eouia/MMM-AssistantMk2#94]
Hi!

I have tried installing this module on a Raspberry Pi 3B+ but I ran into some issues. 
Everything is updated to the latest version.

When starting MagicMirror I got an error, but the important part is:
`electron-v2.0-linux-arm-glibc is missing`

And it is really missing. There is no folder where it looks for.

I have tried reinstalling the module, npm rebuild, npm rebuild --save dev..., install different grpc (grpc-json), electron-rebuild (this just hangs on 0 forever...)

What could I do to solve this?

Thanks!

**Comment by eouia** [comment]
Electron-rebuild will take 20-30 min on rpi usually.

**Comment by radokristof** [comment]
Ok, I will leave it running on tonight. Should that solve this issue?

**Comment by radokristof** [comment]
It solved the issue, had to leave it running for a pretty long time... Thanks!

**Comment by radokristof** [comment]
Now it starts, but I couldn't test it better yesterday. Now I get this error when I want to execute a command to it (now I tested with TelegramBot to say something):
`Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v2.0-linux-arm-glibc
Found: [node-v64-linux-arm-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v2.0-linux-arm-glibc/grpc_node.node'
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:53:17)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:63:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:144:12)`

However the module is there. What can I do?

**Comment by radokristof** [comment]
My bad, after install I forgot to copy my credentials and etc back to the folder. Now it works!!

**Comment by James-Kim-1979** [comment]
Hi. I have a problems with RPI3 B+. help me..plz 
What kind of things problem? I tried many times reinstall. I don't know what is that!
===============================================================
Error: Cannot find module 'node-record-lpcm16'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:8:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:440:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module 'node-record-lpcm16'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:8:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:440:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32) code: 'MODULE_NOT_FOUND' }

**Comment by eouia** [comment]
@radokristof Sorry for bothering you by interference of other's issue. He might not know how to use github.

@James-Kim-1979 한국분이신 것 같아 한글로 답변드립니다. 일단 별개의 이슈건에 대해 타인의 이슈에 덧붙이는 건 바람직하지 않으니 다음에는 별도로 이슈를 세워주세요.
설치는 https://github.com/eouia/MMM-AssistantMk2/wiki/Installation 에 설명되어 있는대로 하시면 됩니다.  `Error: Cannot find module 'node-record-lpcm16'` 이 메시지가 나왔다는 건, `npm install` 단계를 건너뛰셨거나 최소한 그 당시 에러가 발생했을 텐데 그냥 지나치셨을겁니다.
